# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hU4bIiHwELugPywAvzGAttEpMtWISjrG

Project Heading

**OUTLINE:**
1. Basic data inspection, preprocessing, and variable identification
- inspect dimensions
- calculate *wOBA*
2. Convert any categorical data to numeric as needed: pd.get_dummies()
- address null values if present
- remove outcomes from redictors to prevent data leakage (Hits, HRs, BBs)
3. Seaborn heatmap to highlight correlation between key variables like Exit Velocity and Launch Angle with the target var *wOBA*
- check for multicollinearity (calculate VIF)
4. Use sklearn for data training sets and to build linear regression model
- Train-test split
- Ordinary Least Squares Linear Regression
- Ridge or Lasso Regression (multicollinearity)
- Random Forest Regressor
- Cross-Validation for evaluaton reliability
5. Print formatted necessary data, including calculated R^2 and RMSE
- Compare R-squared and RMSE across models
- Extract feature importance
- Discuss limitations of the project
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

# machine learning / modeling
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

# metrics
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# stats
from statsmodels.stats.outliers_influence import variance_inflation_factor

# models
from sklearn.linear_model import RidgeCV, LassoCV

url = "https://raw.githubusercontent.com/Hunter-Mott-31/2023_Baseball_Statcast_App/refs/heads/main/hitter_stats.csv"
df = pd.read_csv(url)
df.head()

"""***Features should be raw physical metrics, such as exit velocity, launch angle, sprint speed, etc.***"""

### 1. Inspection ###
number_players, number_features = df.shape
print(f'Dataset contains {number_players} players and {number_features} features / columns.')

### drop NaN column(s)
df = df.drop(columns=['Unnamed: 18'])

### assigning variables
# wOBA is not present in our dataset, and neither is the data required to manually calculate this.  On-Base Plus Slugging (OPS), however, is calculable from the
# data present, and is still a useful predictor.
y = df['on_base_plus_slg']

X = df[['exit_velocity_avg', 'launch_angle_avg', 'whiff_percent', 'groundballs_percent', 'flyballs_percent', 'linedrives_percent', 'popups_percent', 'sprint_speed']]
print(f'Shape of X: {X.shape}')
X.head()

### 3. Checking multicollinearity (Brought up in Project Proposal feedback) and Seaborn Correlation Heatmap ***
plt.figure(figsize=(10, 6))
sns.heatmap(
    df[['on_base_plus_slg',
        'exit_velocity_avg',
        'launch_angle_avg',
        'whiff_percent',
        'sprint_speed',
        ]].corr(),
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)
plt.title("Correlation Heatmap: Important Predictors vs. OPS Target")
plt.tight_layout()
plt.show()

X_vif = X.copy()
X_vif = X_vif.dropna()
X_vif_con = sm.add_constant(X_vif) # add constant column for statsmodel VIF

# VIF (Variance Inflation Factor) for each feature - This tells us the severity of multicollinearity between variables
vif_data = pd.DataFrame()
vif_data['Feature'] = X_vif.columns

vif_vals = []
for i in range(X_vif.shape[1]):
  # VIF calc
  vif_val = variance_inflation_factor(X_vif_con.values, i + 1)
  vif_vals.append(vif_val)

vif_data['VIF'] = vif_vals

print('\nVariance Influence Factors')
print('VIF of 1 means no correlation, 1-5 means moderate correlation, > 5 means high correlation.')
print(f'{vif_data.sort_values(by='VIF', ascending=False)}')

"""5/8 values have a very high VIF score, meaning they will be immensely problematic for OLS (Ordinary Least Squares).  Cleanup is a requirement to continue:"""

### Eliminating multicollinearity
# keeping distinct physical features
X_cleaned = df[['exit_velocity_avg', 'launch_angle_avg', 'whiff_percent']].dropna()
X_cleaned_con = sm.add_constant(X_cleaned)

# VIF
vif_cleaned = pd.DataFrame()
vif_cleaned['Feature'] = X_cleaned.columns

vif_cleaned_vals = []
for i in range(X_cleaned.shape[1]):
  # VIF calc
  vif_cleaned_val = variance_inflation_factor(X_cleaned_con.values, i + 1)
  vif_cleaned_vals.append(vif_cleaned_val)

vif_cleaned['VIF'] = vif_cleaned_vals

print('\nNew Variance Influence Factors')
print(f'{vif_cleaned.sort_values(by='VIF', ascending=False)}')

### Statsmodels OLS Baseline
ols_stat_model = sm.OLS(y, X_cleaned_con).fit()
print(f'\nStatsmodels OLS Regression Summary: \n\n{ols_stat_model.summary()}')

### 4. SKlearn modeling, Train-Test Split, Cross Val ###
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

y_clean = y.loc[X_cleaned.index]

y_binned = pd.qcut(y_clean, q=4, labels=False) # binned to get balanced representation:
                                               # testing revealed non-binning to produce negative test r^2

X_train, X_test, y_train, y_test = train_test_split(
    X_cleaned, y_clean, test_size=0.2, random_state=42, stratify=y_binned
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_cleaned_scaled = scaler.fit_transform(X_cleaned)

# Model Instantiation:
models = {
    'OLS Linear Regression': LinearRegression(),
    'Ridge Regression': RidgeCV(alphas=np.logspace(-3, 3, 100)),
    'Lasso Regression': LassoCV(alphas=np.logspace(-3, 3, 100), cv=5),
    'Random Forest Regressor': RandomForestRegressor(
        n_estimators=100, max_depth=3, random_state=42
    ),
}

results = []

# going over each model
for name, model in models.items():

  if name in ['Ridge Regression', 'Lasso Regression']:
    model.fit(X_train_scaled, y_train)
    y_train_pred = model.predict(X_train_scaled)
    y_test_pred = model.predict(X_test_scaled)
    cv_scores = cross_val_score(model, X_cleaned_scaled, y_clean, cv=5, scoring='r2')
  else:
    model.fit(X_train, y_train)
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    cv_scores = cross_val_score(model, X_cleaned, y_clean, cv=5, scoring='r2')

  # metrics
  r2_train = r2_score(y_train, y_train_pred)
  r2_test = r2_score(y_test, y_test_pred)
  rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
  rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))
  cv_r2_mean = np.mean(cv_scores)

  results.append({
      'Model': name,
      'Train R^2': round(r2_train, 4),
      'Test R^2': round(r2_test, 4),
      'CV R^2 (Mean)': round(cv_r2_mean, 4),
      'Train RMSE': round(rmse_train, 4),
      'Test RMSE': round(rmse_test, 4)
  })

"""We use OLS as a baseline because it is the simplest, most transparent, easiest to interpret model.

The choice to use Ridge and Lasso was made because we discovered multicolinearity with key factors in this project, and Ridge and Lasso will stabilize the weights that go into making predictions (i.e., more accurate than just OLS as it penalizes large individual features)

Random Forest Regressor was implemented to address multi-variable interactions that lead to high OPS, something that linear regression models struggle with without complex terms.
"""

### 5. Model Evaluation ###
results_df = pd.DataFrame(results)
print(f'\nMODEL PERFORMANCE SUMMARY: \n\n{results_df.to_string(index=False)}')

print('\n\nFEATURE IMPORTANCE AND COEFFICIENTS:\n')
# OLS
ols_model = models['OLS Linear Regression']
for feat, coef in zip(X_cleaned.columns, ols_model.coef_):
  print(f'OLS Coef [{feat}]: {coef:.5f}')

print('\n')

# Random Forest
rf_model = models['Random Forest Regressor']
for feat, imp in zip(X_cleaned.columns, rf_model.feature_importances_):
  print(f'RF Importance [{feat}]: {imp:.5f}')

print('\n')

# Residual Plot Visualization
y_test_pred_ols = ols_model.predict(X_test)
residuals = y_test - y_test_pred_ols

plt.figure(figsize=(10, 6))
plt.scatter(y_test_pred_ols, residuals, alpha=0.7)
plt.axhline(0, color='red', linestyle='--')
plt.xlabel('Predicted OPS')
plt.ylabel('Residuals')
plt.title('OLS Test Set Residual Plot')
plt.tight_layout()
plt.show()

"""1. Physical Factors of OPS: Average exit velocity is the strongest predictor of hitting success, leading 81.8% of the Random Forest model's choices, with Whiff Rate at 10.3% and Launch Angle at 7.9%

2. Performance Metrics: Stratified Train-Test Splitting resolved former sample-skew issues, producing OLS Test R^2 of about 0.55 and Test RMSE of about 0.072.  5-fold cross validation gives a more reliable baseline, showing that physical contact profiles explain roughly 29% of overall seasonal OPS variance.

3. Some Limitations: Random Forest slightly overfits training data compared to linear models, showing that OLS, Ridge, Lasso are preferable for small sample sizes like ours (N = 133).  Residuals show that error variance among high-OPS hitters increases, showing that the elite end relies on unmodeled factors.
"""

